spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/BatchStudy?useUnicode=true&characterEncoding=utf8
      username: root
      password: seul
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always